sudo: false
language: java
jdk:
  - openjdk8
cache:
  directories:
  - $HOME/.m2
#
before_install:
  - chmod +x mvnw
#  - sudo apt-get install jq
  - curl https://github.com/codacy/codacy-coverage-reporter/releases/download/6.0.2/codacy-coverage-reporter-6.0.2-assembly.jar -o ./codacy-coverage-reporter-assembly.jar
#
# Skip installation
#
install: true
#
# Verify
#
script:
  - ./mvnw clean verify -T4 -U -B
#
# Coveralls
#
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -jar ./codacy-coverage-reporter-assembly.jar report -l Kotlin -r example/target/site/jacoco-ut/jacoco.xml --partial
  - java -jar ./codacy-coverage-reporter-assembly.jar final

