sudo: false
language: java
jdk:
  - openjdk8
cache:
  directories:
  - $HOME/.m2
#
before_install:
  - chmod +x mvnw
#
# Skip installation
#
install: true
#
# Verify
#
script:
  - ./mvnw clean verify -T4 -U -B
#
# Coveralls
#
after_success:
  - bash <(curl -s https://codecov.io/bash)

