---
engines:
  exclude_paths:
    - "**/*.js"        # Ignore all JavaScript files
    - "**/test/**"     # Ignore tests
  detekt:  # Kotlin static analysis tool
    exclude_paths:
      - "**/test/**"        # Ignore test folders
      - "**/*Test.kt"       # Ignore Kotlin test files
      - "**/*Test.java"     # Ignore Java test files
      - "**/*Tests.kt"      # Ignore Kotlin test files with plural naming
      - "**/*Tests.java"    # Ignore Java test files with plural naming
  duplications:
    exclude_paths:
      - "**/src/test/kotlin/**"
  markdownlint:
    exclude_paths:
      - ".github/**/*.md"  # No corrections of GitHub markdown files
      - ".github/*.md"
      - "**/index.md"
      - "docs/**/*.md"
  pmd:
    exclude_paths:
      - "**/test/**"
      - "**/tests/**"
      - "**/*Test.java"
      - "**/*Tests.java"
  spotbugs:  # Java static analysis tool
    exclude_paths:
      - "**/test/**"
      - "**/tests/**"
      - "**/*Test.java"
      - "**/*Tests.java"
exclude_paths:
  - "_import/camunda-platform-7-custom-batch"
  - "_import/camunda-platform-7-mockito"
  - "_import/camunda-platform-7-rest-client-spring-boot"
  - "_import/camunda-process-test-coverage"
