# ###############################
# Main config file for MkDocs.
# ###############################
#
# To run:
# mkdocs serve
# More help: https://www.holunda.io/c7/developer-guide/project-setup.html#build-documentation
# ###############################

site_name: Holunda C7
site_url: https://www.holunda.io/c7/
site_author: Holisticon BPM Craftsman
site_description: >-
 Holunda C7 is a collection of open-source Camunda Platform 7 tools and extensions.

copyright: Copyright &copy; 2025, Holisticon AG

use_directory_urls: false

# Repository
repo_name: holunda-io/c7
repo_url: https://github.com/holunda-io/c7/
edit_uri: edit/develop/docs/

markdown_extensions:
    - attr_list
    - toc:
        permalink: "#"
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.details
    - admonition
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  features:
    - navigation.instant # When instant loading is enabled, clicks on all internal links will be intercepted and dispatched via XHR without fully reloading the page
    - navigation.tabs # add top level nav items into a horizoneal menu
    - navigation.tabs.sticky # make horizontal menu sticky (insider feature)
    - navigation.sections
    - navigation.top # add "navigate to top" page icon on bottom left
    - toc.integrate # integrate site TOC into the menu on the left
  logo: assets/img/camunda-logo.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css: [ assets/css/extra.css ]

extra:
  social:
    - icon: fontawesome/brands/twitter
      name: Holisticon on Twitter
      link: https://twitter.com/holisticon
    - icon: fontawesome/brands/medium
      name: Holisticon BPM Craftsmen on Medium
      link: https://medium.com/holisticon-consultants/tagged/mpb
  version:
    provider: mike
  status:
    camunda-ee-only: Suppoorted by Camunda EE only

plugins:
  - search
#  - git-committers:
#      repository: holunda-io/camunda-bpm-taskpool
#      branch: master
#      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  - mike:
      # these fields are all optional; the defaults are as below...
      version_selector: true   # set to false to leave out the version selector
      css_dir: css                    # the directory to put the version selector's CSS
      javascript_dir: js            # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                                            # uses the version specified via `mike deploy`
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true

nav:
  - Home: index.md
  - Getting started:
      - Admin Process Registry: getting-started/c7-admin-process-registry.md
      - Correlate: getting-started/camunda-bpm-correlate.md
      - Data: getting-started/camunda-bpm-data.md
      - Webapp Auto Login: getting-started/c7-webapp-autologin.md
  - User Guide:
      - Overview: user-guide/index.md
      - Extensions: user-guide/extensions.md
      - Admin Process Registry:
          - Overview: user-guide/c7-admin-process-registry/index.md
          - Example: user-guide/c7-admin-process-registry/examples.md
      - Correlate:
          - Overview: user-guide/camunda-bpm-correlate/index.md
          - Components:
            - Ingress Adapter: user-guide/camunda-bpm-correlate/ingress.md
            - Spring Cloud Ingress Adapter: user-guide/camunda-bpm-correlate/ingress-spring-cloud.md
            - Axon Framework Ingress Adapter: user-guide/camunda-bpm-correlate/ingress-axon.md
            - Message Acceptor: user-guide/camunda-bpm-correlate/message-acceptor.md
            - Message Filter: user-guide/camunda-bpm-correlate/filtering-messages.md
            - Message Persistence: user-guide/camunda-bpm-correlate/message-persistence.md
            - Scheduled Processing: user-guide/camunda-bpm-correlate/scheduled-processing.md
            - Cockpit Plugin: user-guide/camunda-bpm-correlate/cockpit-plugin.md
            - Metrics: user-guide/camunda-bpm-correlate/metrics.md
          - Examples: user-guide/camunda-bpm-correlate/examples.md
      - Data:
          - Overview: user-guide/camunda-bpm-data/index.md
          - Features: user-guide/camunda-bpm-data/features.md
          - Examples:
              - Java Examples: user-guide/camunda-bpm-data/examples-java.md
              - Kotlin Examples: user-guide/camunda-bpm-data/examples-kotlin.md
              - Examples without engine: user-guide/camunda-bpm-data/examples-no-engine.md
      - Webapp Auto Login:
          - Overview: user-guide/c7-webapp-autologin/index.md
          - Example: user-guide/c7-webapp-autologin/examples.md

  - Developer Guide:
      - Contributing: developer-guide/contribution.md
      - Project Setup: developer-guide/project-setup.md
