spring:
  application.name: simpleApplication
  datasource:
      url: jdbc:h2:mem:example-simple;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

server.port: 10100

camunda:
  bpm:
    admin-user:
      id: admin

#camunda.bpm.auto-deployment-enabled: false

