name: Bug report
description: File a bug report
title: "[Bug]:"
labels:
  - "Type: bug"
type: "Bug"
body:
  - id: version
    type: dropdown
    attributes:
      label: Library Version
      options:
        - "latest"
        - "any"
      default: 0
    validations:
      required: true
  - id: camunda-version
    type: dropdown
    attributes:
      label: Camunda Version
      options:
        - "7.24 (Default)"
        - "any"
      default: 0
    validations:
      required: true
  - id: component
    type: dropdown
    attributes:
      label: Component
      options:
        - c7-commons-immutables
        - c7-custom-batch
        - c7-rest-client-spring-boot
        - c7-process-test-coverage
        - c7-mockito
        - camunda-admin-process-registry
        - camunda-api
        - camunda-bpm-correlate
        - camunda-bpm-data
        - camunda-bpm-jgiven
        - camunda-bpm-spring-auto-deployment
        - camunda-platform-7-autologin
    validations:
      required: true
  - id: description
    type: textarea
    attributes:
      label: What happend?
      description: what exactly are you doing with the above reproducer?
      placeholder: Tell us what you see!
      value: "A bug happened!"
