<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.holunda.c7._</groupId>
    <artifactId>c7-parent</artifactId>
    <version>2026.02.2-SNAPSHOT</version>
    <relativePath>../../_build/parent/pom.xml</relativePath>
  </parent>

  <name>support: c7-custom-batch - parent pom</name>
  <artifactId>c7-custom-batch-parent</artifactId>
  <packaging>pom</packaging>

  <modules>
    <module>extension/core</module>
    <module>extension/spring</module>
  </modules>

  <developers>
    <developer>
      <name>Patrick Schalk</name>
      <organization>Holisticon AG</organization>
      <organizationUrl>https://holisticon.de</organizationUrl>
    </developer>
  </developers>

  <build>
    <sourceDirectory>src/main/java</sourceDirectory>
    <testSourceDirectory>src/test/java</testSourceDirectory>
  </build>

</project>
