sections:
  introduction:
    title: Introduction
    order: 100
  user-guide:
    title: User Guide
    order: 200
  developer-guide:
    title: Developer Guide
    order: 300

introduction:
  menu:
    - type: 'separator'
      title: 'In This Page'
      order: 100
    - type: 'pageIds'
      order: 110
      structure: nested

    - type: 'separator'
      title: 'Introduction'
      order: 1000
    - type: 'wiki'
      section: 'Introduction'
      order: 1010

developer-guide:
  menu:
    - type: 'separator'
      title: 'In This Page'
      order: 100
    - type: 'pageIds'
      order: 110
      structure: nested

    - type: 'separator'
      title: 'Developer Guide'
      order: 1000
    - type: 'wiki'
      section: 'Developer Guide'
      order: 1010

user-guide:
  menu:
    - type: 'separator'
      title: 'In This Page'
      order: 100
    - type: 'pageIds'
      order: 110
      structure: nested

    - type: 'separator'
      title: 'User Guide'
      order: 1000
    - type: 'wiki'
      section: 'User Guide'
      order: 1010


wikiPages:
  layout: geopattern2

defaultConfig:
  createPdf: true
