<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.holunda.c7._</groupId>
    <artifactId>c7-process-test-coverage-parent</artifactId>
    <version>2026.02.1-SNAPSHOT</version>
  </parent>

  <groupId>io.holunda.c7</groupId>
  <artifactId>c7-process-test-coverage-bom</artifactId>
  <packaging>pom</packaging>
  <name>testing: c7-process-test-coverage - bom</name>

  <dependencyManagement>
    <dependencies>
      <!-- Own modules -->
      <dependency>
        <groupId>io.holunda.c7</groupId>
        <artifactId>c7-process-test-coverage-core</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.holunda.c7</groupId>
        <artifactId>c7-process-test-coverage-engine</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.holunda.c7</groupId>
        <artifactId>c7-process-test-coverage-junit5-common</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.holunda.c7</groupId>
        <artifactId>c7-process-test-coverage-junit5</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.holunda.c7</groupId>
        <artifactId>c7-process-test-coverage-spring-test-common</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.holunda.c7</groupId>
        <artifactId>c7-process-test-coverage-spring-test</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.holunda.c7</groupId>
        <artifactId>c7-process-test-coverage-spring-test-starter</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.holunda.c7</groupId>
        <artifactId>c7-process-test-coverage-report-generator</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.holunda.c7</groupId>
        <artifactId>c7-process-test-coverage-report-aggregator-maven-plugin</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
