# This workflow is triggered by pushing commits to branches and/or Pull Requests.
# It will not trigger for pushes to master or develop, but run on develop every night to provide a nightly build status.
name: Build project with Maven
on:
  pull_request:
  push:
    branches-ignore: [master,develop]
  schedule:
  - cron: '2 2 * * 1-7' # run nightly develop builds everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Java setup
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run Maven
      run: mvn -B clean install com.mycila:license-maven-plugin:check
    - name: Run I-Tests
      run: mvn -B -Pitest
