# If this workflow is triggered by a push to master, it
#        deploys a SNAPSHOT
# If this workflow is triggered by publishing a Release, it
#        deploys a RELEASE with the selected version
#        updates the project version by incrementing the patch version
#        commits the version update change to the repository's default branch.
name: Deploy artifacts with Maven
on:
  push:
    branches: [master,develop]
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - name: Checks out code
      uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up Java environment
      uses: actions/setup-java@v1
      with:
        java-version: 11
        gpg-private-key: ${{ secrets.MAVEN_CENTRAL_GPG_SIGNING_KEY_SEC }}
        gpg-passphrase: MAVEN_CENTRAL_GPG_PASSPHRASE

    - name: Run Maven
      run: mvn -B clean install com.mycila:license-maven-plugin:check

    - name: Run I-Tests and generate coverage reports
      run: mvn -B -Pitest verify

    - name: Deploy SNAPSHOT / Release
      uses: camunda-community-hub/community-action-maven-release@v1
      with:
        release-version: ${{ github.event.release.tag_name }}
        release-profile: release,community-action-maven-release
        nexus-usr: ${{ secrets.NEXUS_USR }}
        nexus-psw: ${{ secrets.NEXUS_PSW }}
        maven-usr: ${{ secrets.MAVEN_CENTRAL_DEPLOYMENT_USR }}
        maven-psw: ${{ secrets.MAVEN_CENTRAL_DEPLOYMENT_PSW }}
        maven-gpg-passphrase: ${{ secrets.MAVEN_CENTRAL_GPG_SIGNING_KEY_PASSPHRASE }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
      id: release

    - name: Attach artifacts to GitHub Release (Release only)
      if: github.event.release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.release.outputs.artifacts_archive_path }}
        asset_name: ${{ steps.release.outputs.artifacts_archive_path }}
        asset_content_type: application/zip

    - name: Publish docs (Release only)
      if: github.event.release
      run: mvn -f docs -Pdeploy-docs -DgithubToken="${{ secrets.GITHUB_TOKEN }}"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload coverage to codacy
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r examples/coverage-report/target/site/jacoco.xml
      env:
        CODACY_API_TOKEN: ${{secrets.CODACY_API_TOKEN}}
