sudo: false
language: java
jdk:
  - openjdk8
cache:
  directories:
  - $HOME/.m2
#
# Load GPG secrets and make mvnw executable
#
before_install:
  - chmod +x mvnw
#
# Skip installation
#
install: true
#
# Verify
#
script: "./mvnw --settings .travis/settings.xml clean verify -T4"
#
# Coveralls
#
after_success:
- bash <(curl -s https://codecov.io/bash)

#
# Notify slack channel
#
notifications:
  slack: holunda:OBhk0v6b16pLFphCq3siuDIZ
