site:
  about:
    siteName: Camunda REST client Spring-Boot
    siteDescription: A Spring-Boot client for accessing Camunda BPM engine via REST.
    avatar: 'assets/media/favicon.png'

allPages:
  components:
    - type: 'pageContent'
      order: 10
    - type: 'prism'
      githubTheme: 'darcula'
      languages:
        - 'yaml'
        - 'java'
        - 'json'
        - 'kotlin'
        - 'markdown'
      plugins:
        - 'line-numbers'
        - 'line-highlight'
        - 'toolbar'
        - 'show-language'
        - 'copy-to-clipboard'


services:
  publications:
    stages:
      - type: 'githubPages'
        username: 'zambrovski'
        repo: 'camunda-community-hub/camunda-rest-client-spring-boot'
