name: Compatibility check

on:
  push:
    branches:
      - '*'
      - '**/*'
      - 'master'

jobs:
  build:
    strategy:
      fail-fast: false
      # Build for three operating systems, currently JVMs 11 and latest four Camunda versions (last two years)
      # On Ubuntu and JDK 11, we run it until 7.10 (Release end of 2018)
      matrix:
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
        jdk:
          - '11'
#          - '17'
        camunda-version:
          - '7.16' # 2021
          - '7.15'
          - '7.14' # 2020
          - '7.13'
        include:
          - os: 'ubuntu-latest'
            jdk: '11'
            camunda-version:
              - '7.12' # 2019
              - '7.11'
              - '7.10' # 2018

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache .m2
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Prepare Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw clean verify -U -B -T4 "-Pcamunda-bpm-engine-${{ matrix.camunda-version }}"
