#
# Controls a client running in the same process.
#
client.enabled: true

spring:
  application:
    name: RestExampleEngineProvided
  jpa:
    open-in-view: true
camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      email: adminus@adminius.io
      first-name: Adminus
      last-name: Administratius
    filter:
      create: true
server:
  port: 8083
feign:
  client:
    config:
      remoteRuntimeService:
        url: "http://localhost:8083/engine-rest/"
      remoteRepositoryService:
        url: "http://localhost:8083/engine-rest/"
      remoteExternalTaskService:
        url: "http://localhost:8083/engine-rest/"

logging:
  level:
    org.camunda.bpm.extension.rest.client.RuntimeServiceClient: DEBUG
    org.camunda.bpm.extension.rest.client.RepositoryServiceClient: DEBUG
