dist: precise
sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
env:
  - CAMUNDA=LATEST
  - CAMUNDA=7.7.0
  - CAMUNDA=7.6.0
  - CAMUNDA=7.5.0
  - CAMUNDA=7.4.0
  - CAMUNDA=7.3.0
install: true
script: mvn -Dcamunda.version=$CAMUNDA
