dist: trusty
sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
env:
  - CAMUNDA=LATEST
  - CAMUNDA=7.9.0
  - CAMUNDA=7.8.0
  - CAMUNDA=7.7.0
  - CAMUNDA=7.6.0
  - CAMUNDA=7.5.0
  - CAMUNDA=7.4.0
  - CAMUNDA=7.3.0
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts > /tmp/hosts
  - sudo mv /tmp/hosts /etc/hosts
  - cat /etc/hosts # optionally check the content *after*
install: true
script: mvn -Dcamunda.version=$CAMUNDA
