# ###############################
# Main config file for MkDocs.
# ###############################
#
# To run: mkdocs serve
# ###############################

site_name: Camunda Process Test Coverage
site_url: https://camunda-community-hub.github.io/camunda-process-test-coverage/
site_author: Camunda OSS Developers
site_description: >-
  This Camunda Platform 7 and Platform 8 ommunity extension visualises test process
  paths and checks your process model coverage ratio. Running  typical
  tests now leaves html files in your build output.

copyright: Copyright &copy; 2022

use_directory_urls: false

# Repository
repo_name: camunda-community-hub/camunda-process-test-coverage
repo_url: https://github.com/camunda-community-hub/camunda-process-test-coverage/
edit_uri: edit/develop/docs/

markdown_extensions:
    - attr_list
    - toc:
        permalink: "#"
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.details
    - admonition

theme:
  name: material
  features:
    - navigation.instant # When instant loading is enabled, clicks on all internal links will be intercepted and dispatched via XHR without fully reloading the page
    - navigation.tabs # add top level nav items into a horizontal menu
    - navigation.tabs.sticky # make horizontal menu sticky (insider feature)
    - navigation.sections
    - navigation.top # add "navigate to top" page icon on bottom left
    - toc.integrate # integrate site TOC into the menu on the left
  logo: assets/img/camunda-logo.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css: [ assets/css/extra.css ]

extra:
#  social:
#    - icon: fontawesome/brands/twitter
#      name: Holisticon on Twitter
#      link: https://twitter.com/holisticon
#    - icon: fontawesome/brands/medium
#      name: Holisticon Event Sourcerers on Medium
#      link: https://medium.com/holisticon-consultants/tagged/mpb
  version:
    provider: mike

plugins:
  - search
  - mike:                             # these fields are all optional; the defaults are as below...
      version_selector: true          # set to false to leave out the version selector
      css_dir: css                    # the directory to put the version selector's CSS
      javascript_dir: js              # the directory to put the version selector's JS
      canonical_version: null         # the version for <link rel="canonical">; `null`
                                      # uses the version specified via `mike deploy`
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - mkdocs-pom-parser-plugin:
      path: pom.xml

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - User Guide:
      - Overview: user-guide/index.md
      - Configuration: user-guide/configuration.md
      - Sonarqube: user-guide/sonarqube.md
  - Developer Guide:
      - Contributing: developer-guide/contribution.md
      - Project Setup: developer-guide/project-setup.md
