site:
  about:
    siteName: Camunda BPM Data
    siteDescription: Beautiful process data handling for Camunda BPM.
    avatar: 'assets/media/favicon.png'

allPages:
  components:
    - type: 'pageContent'
      order: 10
    - type: 'prism'
      githubTheme: 'darcula'
      languages:
        - 'yaml'
        - 'java'
        - 'json'
        - 'kotlin'
        - 'markdown'
      plugins:
        - 'line-numbers'
        - 'line-highlight'
        - 'toolbar'
        - 'show-language'
        - 'copy-to-clipboard'

services:
  publications:
    stages:
      - type: 'githubPages'
        username: 'zambrovski'
        repo: 'holunda-io/camunda-bpm-data'

#
# FIXME: move to separate file after 0.19 release of orchid
#
javadoc:
  modules:
    - name: Camunda BPM Data
      sourceDirs:
        - '../../../../extension/src/main/java'
  pages:
    menu:
      - type: 'sourcedocPageLinks'
        moduleType: 'javadoc'
        itemTitleType: 'SIGNATURE'
        includeItems: true

kotlindoc:
  modules:
    - name: Camunda BPM Data Kotlin
      sourceDirs:
        - '../../../../extension-kotlin/src/main/kotlin'
  pages:
    menu:
      - type: 'sourcedocPageLinks'
        moduleType: 'kotlindoc'
        includeItems: true
        itemTitleType: 'NAME'

