name: Development branches

on:
  pull_request:
  push:
    branches:
      - '*'
      - '**/*'
      - '!master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: 11

    - name: Prepare mvnw
      run: chmod +x ./mvnw

    - name: Build
      run: ./mvnw clean package

    - name: Run integration tests and generate coverage reports
      run: ./mvnw -Pitest verify

    - name: Upload coverage to Codecov
      if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
