name: default

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build
      run: mvn clean package

    - name: Run integration tests
      run: mvn -Pitest

    - name: Create reports
      run: mvn -DskipTests verify

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: example/example-kotlin/target/site/jacoco-aggregate/jacoco.xml
