name: default

on:
  push:
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache .m2
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Prepare mvnw
      run: chmod +x ./mvnw

    - name: Build
      run: ./mvnw clean package

    - name: Run integration tests
      run: ./mvnw -Pitest

    - name: Create reports
      run: ./mvnw -DskipTests verify

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: example/example-kotlin/target/site/jacoco-aggregate/jacoco.xml

#    - name: Create settings.xml
#      uses: s4u/maven-settings-action@v1
#      with:
#        servers: '[{"id": "ossrh", "username": "${{secrets.SONATYPE_USERNAME}}", "password": "${{secrets.SONATYPE_PASSWORD}}"}]'

#    - name: Deploy a new version to central
#      env:
#        GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
#        GPG_KEYNAME: ${{secrets.GPG_KEYNAME}}
#      run: ./mvnw clean deploy -B -DskipTests -DskipExamples -Prelease -Dgpg.passphrase=${{secrets.GPG_PASSPHRASE}}
