name: Master branch

on:
  push:
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: 11
        server-id: ossrh
        server-username: OSS_CENTRAL_USERNAME # env variable for Maven Central
        server-password: OSS_CENTRAL_PASSWORD # env variable for Maven Central

    # Get GPG private key into GPG
    - name: Import GPG Owner Trust
      run: echo ${{ secrets.GPG_OWNERTRUST }} | base64 --decode | gpg --import-ownertrust

    - name: Import GPG key
      run: echo ${{ secrets.GPG_SECRET_KEYS }} | base64 --decode | gpg --import --no-tty --batch --yes

    - name: Prepare mvnw
      run: chmod +x ./mvnw

    - name: Build
      run: ./mvnw clean package

    - name: Run integration tests and generate coverage reports
      run: ./mvnw -Pitest verify

    - name: Deploy a new version to central
      run: ./mvnw clean deploy -B -DskipTests -DskipExamples -Prelease -Dgpg.keyname="${{secrets.GPG_KEYNAME}}" -Dgpg.passphrase="${{secrets.GPG_PASSPHRASE}}"
      env:
        OSS_CENTRAL_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        OSS_CENTRAL_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
