name: Master branch

permissions:
  contents: read

on:
  push:
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Expose branch name
      run: echo ${{ github.ref }}

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version-file: .java-version
        server-id: central
        server-username: OSS_CENTRAL_USERNAME
        server-password: OSS_CENTRAL_PASSWORD

    - name: Prepare mvnw
      run: chmod +x ./mvnw

    - name: Build
      run: ./mvnw clean package -ntp

    - name: Run integration tests and generate coverage reports
      run: ./mvnw -Pitest verify -ntp failsafe:verify

      # Get GPG private key into GPG
    - name: Import GPG Owner Trust
      run: echo ${{ secrets.GPG_OWNERTRUST }} | base64 --decode | gpg --import-ownertrust

    - name: Import GPG key
      run: echo ${{ secrets.GPG_SECRET_KEYS }} | base64 --decode | gpg --import --no-tty --batch --yes

    - name: Deploy a new version to central
      run: ./mvnw clean deploy -B -ntp -DskipTests -DskipItests -DskipITests -DskipExamples -Prelease -Dgpg.keyname="${{secrets.GPG_KEYNAME}}"
      env:
        OSS_CENTRAL_USERNAME: "${{ secrets.SONATYPE_USERNAME }}"
        OSS_CENTRAL_PASSWORD: "${{ secrets.SONATYPE_PASSWORD }}"
        MAVEN_GPG_PASSPHRASE: "${{ secrets.GPG_PASSPHRASE }}"

    - name: Upload coverage to Codecov
      if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
      uses: codecov/codecov-action@v5
      with:
        token: ${{secrets.CODECOV_TOKEN}}

    - name: Upload test coverage to Codacy
      if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
      env:
        CODACY_PROJECT_TOKEN: "${{secrets.CODACY_PROJECT_TOKEN}}"
